<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/26/026
 * Time: 13:44
 */

namespace HomeBundle\Controller;


use Trochilidae\bin\Core\Controller;

class BaseController extends Controller
{

    protected function __before()
    {
        parent::__before(); // TODO: Change the autogenerated stub
//        print_r('before');
    }

    protected function __after()
    {
        parent::__after(); // TODO: Change the autogenerated stub
//        print_r('after');

    }

}